### ISSUE TITLE
Hash keys returning an array

### ISSUE THREAD

**Issue by KevinSjoberg** [rails/strong_parameters#139]
Consider the following JSON-structure converted to a Hash.

```json
{
  "measured_at": "2013-04-30T12:03:29.968Z",
  "measurement_type": "measurement",
  "entries": [
    {"name": "weight", "unit": "cm", "value": "80.0"},
    {"name": "thighs", "unit": "cm", "value": "40.5"}
  ]
}
```

Let us assume that `entries` is a required key and a record can not be created without it.

```ruby
params.require(:entries).permit(:name, :unit, :value)
```

This will unfortunately not work due to `require` returning the given key, which in this case results in an array.

```ruby
[
  {"name": "weight", "unit": "cm", "value": "80.0"},
  {"name": "thighs", "unit": "cm", "value": "40.5"}
]
```

I'm more than willing to solve the use case as long as this is behavior that should be a part of Strong Parameters domain. If so, do you have any ideas @dhh?

**Comment by lalitlogical** [comment]
@wizztjh Thanks for your solution :+1:

**Comment by rodrigomageste** [comment]
@wizztjh  Thanks !

**Comment by KevinSjoberg** [comment]
Since @wizztjh seems to have a working solution for this problem I'm closing the issue.

**Comment by alexpacer** [comment]
Thanks for the solution @wizztjh, Works perfectly! :)

**Comment by tejashjl** [comment]
@wizztjh thanks man..solved the problem

**Comment by johnmckinght** [comment]
@wizztjh thanks man you save my day.
