### ISSUE TITLE
Merging Nested Paramters

### ISSUE THREAD

**Issue by null-null-null** [rails/strong_parameters#145]
It's possible to merge extra parameters with user generated ones like so:

     params.require(:post).permit([:title, :body]).merge(user: current_user)

It's also possible to include nested attributes like so:

     params.require(:post).permit([:title, :body, sections_attributes: [:title, :section_type]])

Now, what if I wanted to merge extra parameters into a nested model. I tried this:

    params.require(:post).permit([:title, :body, sections_attributes: [:title, :section_type]]).merge(user: current_user, sections_attributes: [user: current_user])

But when I check the params with debugger afterwards, I find that `user` has overwritten the other `section_attributes` rather than merging with them. Is there a better way to approach this problem?

**Comment by odinsy** [comment]
Use deep_merge http://apidock.com/rails/Hash/deep_merge
