### ISSUE TITLE
Strong parameters for nested attributes returns “unpermitted parameters” when empty array

### ISSUE THREAD

**Issue by phron** [rails/strong_parameters#155]
using Rails4 with strong_parameters. Assuming a User model

```
class User < ActiveRecord::Base
  has_secure_password

 accepts_nested_attributes_for :identity

//  rest of code omitted for brevity
end
```

If I refer to the guide I should be able to do

```
def user_params
    params.require(:user).permit(:email, identity_attributes: [])
end
```

to allow mass_assignment of each identity_attributes whatever their names or number. But this run in a "Unpermitted parameters: identity_attributes"

But if I specify the identity_attributes it works 

```
def user_params 
params.require(:user).permit(:email, identity_attributes: [:last_name, :first_name]) end
```

I have many attributes in Identity, I would be able to mass_assign them through User without specifying all of them.

Am I missing something ? Is it a bug ?

Cheers

**Comment by matisoffn** [comment]
I'm having a similar problem and have tried quite a few solutions on the web.  I have a model `Note` and it has many of the `Document` model.

```ruby
class Note < ActiveRecord::Base
  has_many :documents
  accepts_nested_attributes_for :documents
end
```

And then in my controller (simple RESTful actions) when I try to create a note I continuously get back `Unpermitted parameters: documents`.

In my controller, I permit the params like so:

```ruby
params
  .require(:note)
  .permit(:description, documents_attributes: [:id, :name, :ext, :mime_type])
```

But I still receive the unpermitted parameters and the records are not saved to the DB.  I'm posting an array of objects (JSON), that looks somewhat like this:

```json
{
  "note": {
    "description": "test note",
    "documents": [{
      "name": "testdoc.jpg",
      "mime_type": "image/jpg"
    }]
  }
}
```

**Comment by thomasfedb** [comment]
The issue you have @matisoffn is that you are permitting the key `:documents_attributes`, but using the key `:documents` in your request. You need to choose one. The error is entirely correct.

**Comment by thomasfedb** [comment]
Also @matisoffn, you should not that (as specified in the `README.md`) this is a compatability gem for versions of Rails prior to 4.0. If you are using Rails 4.0 or later you should raise issues against rails/rails.

**Comment by matisoffn** [comment]
@thomasfedb thanks so much.
