### ISSUE TITLE
ActiveModel::ForbiddenAttributesError in permit.tap chain

### ISSUE THREAD

**Issue by styx** [rails/strong_parameters#172]
Currently (Rails 4) such a piece of code is not working:

```ruby
def product_params
  params.require(:product).permit(:name).tap do |whitelisted|
    whitelisted[:data] = params[:product][:data]
  end
end
```

take from http://edgeguides.rubyonrails.org/action_controller_overview.html#outside-the-scope-of-strong-parameters

**Comment by fseefried** [comment]
It is working fine as long as you do not have

config.action_controller.action_on_unpermitted_parameters = :raise

in your environment enabled.

If enabled it will raise an error before going into the whitelisted block. Is it a Bug?

**Comment by styx** [comment]
@fseefried I really don't remember what happened on Sep 30, 2013. This seems to be obsolete.

**Comment by fseefried** [comment]
Hmm - I've the same problem on most recent Rails 4.2, as soon as I enable config.action_controller.action_on_unpermitted_parameters = :raise
