### ISSUE TITLE
rename() to rename keys in params

### ISSUE THREAD

**Issue by alevinval** [rails/strong_parameters#196]
Hi,

Assume I'm doing an API in Rails with StrongParameters, and I got a model like Pricing, with many Prices. 

I want my API to support in one endpoint nested attributes for the Prices of a Pricing.

The consumer of the API doesn't care that I am using Rails, so he sends me the nested attributes of the Prices as :prices, but Rails is expecting :prices_attributes

And I am just wondering if it could be possible to bring extra options on Strong Parameters, to rename keys like:

```
params.permit(:prices, :description, ...)
params.rename(:prices, :prices_attributes)
```

Seems like a legit feature, or solution.

**Comment by akz92** [comment]
I found this alternative on Rails core mailing list. I'll post here for future reference:
```
params.tap { |p| p[:prices_attributes] = p[:prices] }.permit(:prices_attributes)
```
