### ISSUE TITLE
Can't permit/require nested parameters to be nested in arrays

### ISSUE THREAD

**Issue by nwjsmith** [rails/strong_parameters#209]
While you can permit nested parameters to have certain keys, you can't require they be nested in an array.

Specifically, using strong parameters like so:
```ruby
params.permit(authors: [:name])
```
will permit parameters structured like this:
```ruby
{authors: {name: 'William Shakespeare'}}
```
as well as parameters nested in an array like this:
```ruby
{authors: [{name: 'William Shakespeare'}, {name: 'Christopher Marlo'}]}
```

Strong parameters should have a way to permit one or the other, not both. I was surprised to find that using `params.permit(author: [:name])` works to parse both sets of parameters.

I think that `params.permit(author: [:name])` should only permit parameters like `{authors: {name: ... }}` and that `params.permit(author: [[:name]])` should only permit `{authors: [{name: ... }]}`. Unfortunately this would be a breaking change. 

What do you think?

**Comment by kaspernj** [comment]
+1

**Comment by kaspernj** [comment]
If you somehow used integers as keys (as with nested parameters for multiple models), then I have made a fix that you can test:

```ruby
gem 'strong_parameters', git: "https://github.com/kaspernj/strong_parameters.git", branch: "kj/fixed_integers_as_keys"
```

Also submitted as a PR here:
https://github.com/rails/strong_parameters/pull/221

**Comment by thomasfedb** [comment]
Hi @kaspernj, you should avoid spamming your PR as a 'magic bullet' to any issue raised against this gem.
