### ISSUE TITLE
Unpermitted parameters when whitelisting them in the model & controller

### ISSUE THREAD

**Issue by matisoffn** [rails/strong_parameters#222]
I'm having a similar problem and have tried quite a few solutions on the web.  I have a model `Note` and it has many of the `Document` model.

```ruby
class Note < ActiveRecord::Base
  has_many :documents
  accepts_nested_attributes_for :documents
end
```

And then in my controller (simple RESTful actions) when I try to create a note I continuously get back `Unpermitted parameters: documents`.

In my controller, I permit the params like so:

```ruby
params
  .require(:note)
  .permit(:description, documents_attributes: [:id, :name, :ext, :mime_type])
```

But I still receive the unpermitted parameters and the records are not saved to the DB.  I'm posting an array of objects (JSON), that looks somewhat like this:

```json
{
  "note": {
    "description": "test note",
    "documents": [{
      "name": "testdoc.jpg",
      "mime_type": "image/jpg"
    }]
  }
}
```

**Comment by rafaelfranca** [comment]
You are receiving `documents` and permitting `documents_attributes`. You should permit `documents`

**Comment by matisoffn** [comment]
@rafaelfranca I've tried that, and I get back a "{Model} expected, got ActionController::Parameters` error.

**Comment by rafaelfranca** [comment]
Because you need to pass `documents_attributes` to the model creating. So you should:

1. Permit `documents` and pass it to the model as `documents_attributes`
2. Receive `documents_attributes`, permit it and pass to the model.
