### ISSUE TITLE
Nested attributes are not permitted

### ISSUE THREAD

**Issue by itsNikolay** [rails/strong_parameters#225]
in rails 4.2.1
```ruby
ActionController::Parameters
  .new(chapter_attributes: { 0 => { title: 'hi' }, 1 => { title: 'hi2' }})
  .permit(chapter_attributes: [:title])

# =>
Unpermitted parameters: 0, 1
=> {"chapter_attributes"=>{}}
```
I followed this guide http://edgeguides.rubyonrails.org/action_controller_overview.html#more-examples

**Comment by fxn** [comment]
As seen in the example, the integers [have to be strings](https://github.com/rails/rails/blob/7220ffcffd0085b3caee872102b3b28f3ca35c83/actionpack/lib/action_controller/metal/strong_parameters.rb#L483).
