### ISSUE TITLE
Fix Travis CI builds

### ISSUE THREAD

**Issue by astorije** [rails/strong_parameters#244]
At the moment, all builds but the Ruby 2.0.0 × Rails 3.2 are failing.
It seems to me that the purpose of this gem is to help people under Rails 3 transition to Rails 4, and these people are often using Rails < 2 (because if you're outdated with Rails, why not be outdated with Ruby too 😅). Well, at least we are...

I looked at the builds but couldn't figure out the fix straight ahead, but at least this issue keeps track of things if someone fixes all or part of the builds.

**Comment by amatsuda** [comment]
It's been fixed now. https://travis-ci.org/rails/strong_parameters/builds/175399230
