### ISSUE TITLE
after upgrade rail 3 to 4 data inserted on Table is NULL

### ISSUE THREAD

**Issue by dipenpatel235** [rails/strong_parameters#246]
Hello
I have written below code and not any error now but data inserted on Table is NULL

` def create
    @worklog = Worklog.new(user_params)
    @worklog.day = Date.today
    @worklog.week = Date.today.strftime("%W").to_i
    @worklog.author = User.current
    @worklog.save
    redirect_to worklogs_path()
  end

  private
  def user_params
    params.require(:worklog).permit(:utf8, :authenticity_token, { worklog: [:typee, :do, :todo, :feel, :plan_done, :plan, :week_feel, :score, :good, :nogood]}, :commit)
  end
`
See Below Output:

 `SELECT  `worklogs`.* FROM `worklogs` where created_at = created_at  ORDER BY `worklogs`.`id` DESC LIMIT 3;
+------+---------+-------+------------+------+------+------+--------+---------------------+------+-------+------+--------+-------+------+
| id   | user_id | typee | day        | week | do   | todo | status | created_at          | feel | score | good | nogood | month | year |
+------+---------+-------+------------+------+------+------+--------+---------------------+------+-------+------+--------+-------+------+
| 5714 |      36 |     0 | 2017-01-13 |    2 | NULL | NULL |      0 | 2017-01-13 02:54:53 | NULL |  NULL | NULL | NULL   |  NULL | NULL |
| 5713 |      18 |     0 | 2017-01-13 |    2 | NULL | NULL |      0 | 2017-01-13 02:04:28 | NULL |  NULL | NULL | NULL   |  NULL | NULL |
`

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
