### ISSUE TITLE
Require and permit this json

### ISSUE THREAD

**Issue by Herz3h** [rails/strong_parameters#248]
Hello i a rails api project, and on one route i receive this json : 

```
{
	"group_audio": {
		"name": "Groupe audio"
	},
	"audios": [
		{
			"name": "audioA",
			"description": "descriptionA",
			"original_filename": "audioA.wav",
			"checksum": "1234",
			"data": "1234",
			"order": "1"
		}
	]
}
```

But i tried so many things to make sure that group_audio and audios are required and the rest is permitted so i can access all the data without any success. Like this for example : 

`params.require(:audios).permit(:name, :description, :original_filename, etc..)`

`params.require(:audios).permit([{:name => String, :description => String, :original_filename => String, etc..}])`

`params.require(:group_audio => {:name => String}, :audios => [{:name => String, :description => String, :original_filename => String, etc..}])`

None of this seems to be working, any help please?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
