### ISSUE TITLE
Question - in strong_parameters is checking only key is present in params enough?

### ISSUE THREAD

**Issue by sumitmah** [rails/strong_parameters#250]
```
# File actionpack/lib/action_controller/metal/strong_parameters.rb, line 424
def require(key)
  return key.map { |k| require(k) } if key.is_a?(Array)
  value = self[key]
  if value.present? || value == false
    value
  else
    raise ParameterMissing.new(key)
  end
end
```

This is just a question, wanted to understand why are we checking values are present for request params over checking if key is present in request.

**Comment by sumitmah** [comment]
so we can have `params.require(:parameter).permit(:another_parameter)`

**Comment by sumitmah** [comment]
so we can have `params.require(:parameter).permit(:another_parameter)`?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
